//ARGO
[
  {
    "model": "Argo 1.0",
    "brand": "Fiat",
    "transmission": "Manual",
    "category": "Compact",
    "rating": "0",
    "year": "2018",
    "price": "38.908",
    "ipva": "1.556",
    "insurance": "2.218",
    "horsePower": "77",
    "fuelCost": "14.2",
    "speed": "162",
    "depreciation": "5.78",
    "maintenance": "2.540",
    "warranty": "3",
    "trunk": "300",
    "review": "0",
    "abs": "true",
    "parkSensor": "false",
    "airBag": "true",
    "fogLights": "false",
    "backupCam": "false",
    "alarm": "false",
    "airCondit": "true",
    "heightSeat": "false",
    "autoPilot": "false",
    "leatherSeat": "false",
    "sunRoof": "false",
    "steeringWheelAdjust": "true",
    "alloyWheel": "false",
    "headlightSensor": "false",
    "radio": "false",
    "usb": "false",
    "gps": "false",
    "boardPc": "false",
    "steeringMultiFunction": "false",
    "bluetooth": "false"
  }
]
//HB20
[
  {
    "model": "HBS20 5 ANOS 1.0",
    "brand": "Hyundai",
    "transmission": "Manual",
    "category": "Compact",
    "rating": "0",
    "year": "2018",
    "price": "44.174",
    "ipva": "1.767",
    "insurance": "2.518",
    "horsePower": "80",
    "fuelCost": "12.5",
    "speed": "161",
    "depreciation": "1.04",
    "maintenance": "2.383",
    "warranty": "5",
    "trunk": "300",
    "review": "0",
    "abs": "true",
    "parkSensor": "true",
    "airBag": "true",
    "fogLights": "true",
    "backupCam": "false",
    "alarm": "true",
    "airCondit": "true",
    "heightSeat": "false",
    "autoPilot": "false",
    "leatherSeat": "false",
    "sunRoof": "false",
    "steeringWheelAdjust": "true",
    "alloyWheel": "false",
    "headlightSensor": "false",
    "radio": "false",
    "usb": "false",
    "gps": "false",
    "boardPc": "true",
    "steeringMultiFunction": "false",
    "bluetooth": "false",
      }
]
//JETTA
[
  {
    "model": "Jetta Comfortline 1.4 TSI Tiptronic",
    "brand": "Volkswagen",
    "transmission": "Automatic",
    "category": "Sedan",
    "rating": "0",
    "year": "2018",
    "price": "84.805",
    "ipva": "3.392",
    "insurance": "4.834",
    "horsePower": "150",
    "fuelCost": "10.4",
    "speed": "203",
    "depreciation": "4.06",
    "maintenance": "3.603",
    "warranty": "3",
    "trunk": "510",
    "review": "0",
    "abs": "true",
    "parkSensor": "true",
    "airBag": "true",
    "fogLights": "true",
    "backupCam": "false",
    "alarm": "true",
    "airCondit": "true",
    "heightSeat": "true",
    "autoPilot": "true",
    "leatherSeat": "true",
    "sunRoof": "false",
    "steeringWheelAdjust": "true",
    "alloyWheel": "true",
    "headlightSensor": "false",
    "radio": "true",
    "usb": "true",
    "gps": "false",
    "boardPc": "true",
    "steeringMultiFunction": "true",
    "bluetooth": "true",
}
]
//CRUZE
[
  {
    "model": "Cruze LT 1.4 Turbo",
    "brand": "Chevrolet",
    "transmission": "Automatic",
    "category": "Sedan",
    "rating": "0",
    "year": "2018",
    "price": "85.496",
    "ipva": "3.420",
    "insurance": "4.360",
    "horsePower": "153",
    "fuelCost": "11.2",
    "speed": "214",
    "depreciation": "8.06",
    "maintenance": "3.044",
    "warranty": "3",
    "trunk": "440",
    "review": "0",
    "abs": "true",
    "parkSensor": "true",
    "airBag": "true",
    "fogLights": "true",
    "backupCam": "true",
    "alarm": "false",
    "airCondit": "true",
    "heightSeat": "true",
    "autoPilot": "true",
    "leatherSeat": "true",
    "sunRoof": "false",
    "steeringWheelAdjust": "true",
    "alloyWheel": "true",
    "headlightSensor": "false",
    "radio": "true",
    "usb": "true",
    "gps": "false",
    "boardPc": "true",
    "steeringMultiFunction": "true",
    "bluetooth": "true",
}
]
//ONIX LT 1.0
[
  {
    "model": "Onix LT 1.0",
    "brand": "Chevrolet",
    "transmission": "Manual",
    "category": "Compact",
    "rating": "0",
    "year": "2018",
    "price": "40.205",
    "ipva": "1.608",
    "insurance": "2.292",
    "horsePower": "80.2",
    "fuelCost": "12.9",
    "speed": "167",
    "depreciation": "3.78",
    "maintenance": "3.180",
    "warranty": "3",
    "trunk": "280",
    "review": "0",
    "abs": "true",
    "parkSensor": "false",
    "airBag": "true",
    "fogLights": "false",
    "backupCam": "false",
    "alarm": "true",
    "airCondit": "true",
    "heightSeat": "true",
    "autoPilot": "false",
    "leatherSeat": "false",
    "sunRoof": "false",
    "steeringWheelAdjust": "false",
    "alloyWheel": "false",
    "headlightSensor": "false",
    "radio": "true",
    "usb": "true",
    "gps": "false",
    "boardPc": "false",
    "steeringMultiFunction": "false",
    "bluetooth": "true",
  }
]
// HR-V EX 1.8 AT
[  
{
    "model": "HR-V EX 1.8 AT",
    "brand": "Honda",
    "transmission": "Automatic",
    "category": "SUV",
    "rating": "0",
    "year": "2018",
    "price": "85.520",
    "ipva": "3.421",
    "insurance": "4.875",
    "horsePower": "139",
    "fuelCost": "7.7",
    "speed": "175",
    "depreciation": "-0.02",
    "maintenance": "2.600",
    "warranty": "3",
    "trunk": "437",
    "review": "0",
    "abs": "true",
    "parkSensor": "true",
    "airBag": "true",
    "fogLights": "true",
    "backupCam": "true",
    "alarm": "true",
    "airCondit": "true",
    "heightSeat": "true",
    "autoPilot": "true",
    "leatherSeat": "true",
    "sunRoof": "false",
    "steeringWheelAdjust": "true",
    "alloyWheel": "true",
    "headlightSensor": "true",
    "radio": "true",
    "usb": "true",
    "gps": "true",
    "boardPc": "true",
    "steeringMultiFunction": "true",
    "bluetooth": "true",
  }
]
// KICKS NISSAN SL 1.6 AT
[  
  {
      "model": "Kicks SL 1.6 AT",
      "brand": "Nissan",
      "transmission": "Automatic",
      "category": "SUV",
      "rating": "0",
      "year": "2018",
      "price": "88.410",
      "ipva": "3.536",
      "insurance": "4.509",
      "horsePower": "114",
      "fuelCost": "9,7",
      "speed": "175",
      "depreciation": "6.84",
      "maintenance": "2.591",
      "warranty": "3",
      "trunk": "432",
      "review": "0",
      "abs": "true",
      "parkSensor": "true",
      "airBag": "true",
      "fogLights": "true",
      "backupCam": "true",
      "alarm": "true",
      "airCondit": "true",
      "heightSeat": "true",
      "autoPilot": "true",
      "leatherSeat": "true",
      "sunRoof": "false",
      "steeringWheelAdjust": "true",
      "alloyWheel": "true",
      "headlightSensor": "true",
      "radio": "true",
      "usb": "true",
      "gps": "false",
      "boardPc": "true",
      "steeringMultiFunction": "true",
      "bluetooth": "true",
    }
  ]