[
  {
    "model": "Argo",
    "brand": "Fiat",
    "transmission": "Manual",
    "category": "Compact",
    "rank": {
      "rating": "0",
      "year": "2018",
      "price": "38.908",
      "ipva": "1.556",
      "insurance": "2.218",
      "horsePower": "77",
      "fuelCost": "14.2",
      "speed": "162",
      "depreciation": "5.78",
      "maintenance": "2.540",
      "warranty": "3",
      "trunk": "300",
    },
    "review": "0",
    "accessories": {
      "security": {
        "abs": "true",
        "parkSensor": "false",
        "airBag": "true",
        "fogLights": "false",
        "backupCam": "false",
        "alarm": "false",
      },
      "confort": {
        "airCondit": "true",
        "heightSeat": "false",
        "autoPilot": "false",
        "leatherSeat": "false",
        "sunRoof": "false",
        "steeringWheelAdjust": "true",
        "alloyWheel": "false",
        "headlightSensor": "false",
      },
      "entertainment": {
        "radio": "false",
        "usb": "false",
        "gps": "false",
        "boardPc": "false",
        "steeringMultiFunction": "false",
        "bluetooth": "false",
      },
    },
  }
]

[
  {
    "model": "HBS20",
    "brand": "Hyundai",
    "transmission": "Manual",
    "category": "Compact",
    "rank": {
      "rating": "0",
      "year": "2018",
      "price": "44.174",
      "ipva": "1.767",
      "insurance": "2.518",
      "horsePower": "80",
      "fuelCost": "12.5",
      "speed": "161",
      "depreciation": "1.04",
      "maintenance": "2.383",
      "warranty": "5",
      "trunk": "300",
    },
    "review": "0",
    "accessories": {
      "security": {
        "abs": "true",
        "parkSensor": "true",
        "airBag": "true",
        "fogLights": "true",
        "backupCam": "false",
        "alarm": "true",
      },
      "confort": {
        "airCondit": "true",
        "heightSeat": "false",
        "autoPilot": "false",
        "leatherSeat": "false",
        "sunRoof": "false",
        "steeringWheelAdjust": "true",
        "alloyWheel": "false",
        "headlightSensor": "false",
      },
      "entertainment": {
        "radio": "false",
        "usb": "false",
        "gps": "false",
        "boardPc": "true",
        "steeringMultiFunction": "false",
        "bluetooth": "false",
      },
    },
  }
]